---
- name: shell output
  hosts: all
  tasks:
          - name: shell output
            command: 'podman login -u pray11@yahoo.com -p Lai55guang! registry.redhat.io --log-level debug'
#           command: 'python3 --version 2>&1'
            register: ssh_output

          - name: Display the output
            debug:
              var: ssh_output.stdout_lines
              
#          - name: Get network information using ip command
#            shell: ip addr show
#            register: ip_output

#          - name: Display ip command output
#            debug:
#              var: ip_output.stdout
