---
- name: shell output
  hosts: all
  tasks:
          - name: shell output
            command: 'ip add'
#           command: 'python3 --version 2>&1'
            register: ssh_output

          - name: Display the output
            debug:
              var: ssh_output.stdout_lines
