---
- name: Basic System Setup
  hosts: all
  gather_facts: false
  become: true
  remote_user: admin
  become_user: root
  vars:
    ansible_become_pass: Aap11145!
  become_method: su
  tasks:
    - name: Install security updates for the kernel
      ansible.builtin.yum:
        name: mlocate
        state: present

#    - name: NTP server is enabled
#      ansible.builtin.service:
#        name: chronyd
#        enabled: true
