---
- name: Get all Ansible facts
  hosts: all
  gather_facts: yes
  tasks:
    - name: Print all facts
      debug:
        var: ansible_facts
    - name: Set some data to pass down to the 2nd Job template
      set_stats:
        data:
          my_personal_variable: "{{ ansible_facts.ansible_system }}-blah"
 
 
