---
- name: Get all Ansible facts
  hosts: all
  gather_facts: yes
  tasks:
#    - name: Print all facts
#      debug:
#        var: ansible_facts
    - name: Print OS family
      debug:
        var: ansible_os_family
    - name: Set some data to pass down to the 2nd Job template
      set_stats:
        data:
          my_personal_variable: "{{ ansible_facts.ansible_os_family }}-blah"
     -name: print my_personal_variable
      debug:
        msg: "This is my_personal_var {{my_personal_variable}}"
 
 
