---
- name: shell output
  hosts: all
  gather_facts: no
  tasks:

         - name: shell output
           command: 'ls -la /etc'
           register: ssh_output

         - name: Display the output
           debug:
              var: ssh_output.stdout_lines
