---
- name: shell output
  hosts: all
  gather_facts: no
  tasks:
    - name: list working directory
      ansible.builtin.shell:
        shell: ls -l /etc
        register: ls_output

    - name: Display the output
        debug:
          var: ls_output.stdout_lines
